name: "Build outputs and lint"

on: 
  push:
    branches:
      - "master"

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App
        uses: actions/checkout@v3
      - name: Add nodejs
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 18
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install Deps
        run: pnpm install
      - name: Publish
        run: node publish
        continue-on-error: true
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}