name: "Build outputs and lint"

on: 
  push:
    branches:
      - "master"

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App
        uses: actions/checkout@v3
      - name: Add nodejs
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: 18
      - name: Install pnpm
        run: sudo curl -fsSL https://get.pnpm.io/install.sh | sh -
      - name: Install Deps
        run: pnpm install
      - name: Publish
        run: node publish
        continue-on-error: false
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}