name: "Build outputs and lint"

on: 
  push:
    branches:
      - "master"

jobs:
  publish-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App
        uses: actions/checkout@v3
      - name: Install sudo
        run: sudo apt-get install curl
      - name: Add nvm
        run: sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
      - name: Add nodejs
        run: sudo nvm use v18.2.0
      - name: Install pnpm
        run: sudo curl -fsSL https://get.pnpm.io/install.sh | sh -
      - name: Install Deps
        run: pnpm install
      - name: Publish
        run: node publish
        continue-on-error: false
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}